---
hostname: "seed-plus-dev-app"

# ProxyJump via NAT instance for SSH access from control node
ansible_ssh_common_args: >-
  -o ProxyCommand="ssh -i ~/.ssh/seed-plus-dev-key.pem
  -o StrictHostKeyChecking=no -W %h:%p ubuntu@{{ nat_eip }}"

app_container_name: "seed-plus-app"
app_container_image: "traefik/whoami:latest"
