---
- name: Configure DB tier instance
  hosts: tier_db
  become: true
  gather_facts: true
  roles:
    - role: common
      tags: [bootstrap, common]
    - role: db_postgres
      tags: [db, postgres]
    - role: cloudwatch_agent
      tags: [monitoring, cloudwatch]
      vars:
        cwa_extra_logs:
          - file_path: "/var/log/postgresql/postgresql-{{ pg_version }}-{{ pg_cluster_name }}.log"
            log_group_name: "{{ cwa_log_group_prefix }}/{{ hostname }}/postgresql"
