---
- name: Restart postgresql
  ansible.builtin.service:
    name: "postgresql@{{ pg_version }}-{{ pg_cluster_name }}"
    state: restarted

- name: Reload postgresql
  ansible.builtin.service:
    name: "postgresql@{{ pg_version }}-{{ pg_cluster_name }}"
    state: reloaded
