#!/usr/bin/env bash
# Fetch live IPs from AWS and write to Ansible inventory vars.
# Run after every `terraform apply` that changes EC2 or EIP resources.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REGION="ap-northeast-2"
PROJECT="seed-plus"
ENV="dev"
OUT_FILE="${REPO_ROOT}/ansible/inventory/dev/group_vars/all/terraform_outputs.yml"

require_cmd() { command -v "$1" >/dev/null 2>&1 || { echo "ERROR: '$1' not found"; exit 1; }; }
require_cmd aws
require_cmd jq

echo "[ansible-sync] Fetching IPs for ${PROJECT}/${ENV} in ${REGION}..."

# NAT instance EIP (tagged Role=nat-instance)
nat_eip=$(aws ec2 describe-instances \
  --region "${REGION}" \
  --filters "Name=tag:Role,Values=nat-instance" \
            "Name=tag:Environment,Values=${ENV}" \
            "Name=instance-state-name,Values=running" \
  --query 'Reservations[0].Instances[0].PublicIpAddress' \
  --output text)

# Web EIP (aws_eip.web — tagged Name=seed-plus-dev-web-eip)
web_eip=$(aws ec2 describe-addresses \
  --region "${REGION}" \
  --filters "Name=tag:Name,Values=${PROJECT}-${ENV}-web-eip" \
  --query 'Addresses[0].PublicIp' \
  --output text)

# App instance private IP (Tier=app)
app_private_ip=$(aws ec2 describe-instances \
  --region "${REGION}" \
  --filters "Name=tag:Tier,Values=app" \
            "Name=tag:Environment,Values=${ENV}" \
            "Name=instance-state-name,Values=running" \
  --query 'Reservations[0].Instances[0].PrivateIpAddress' \
  --output text)

# DB instance private IP (Tier=db)
db_private_ip=$(aws ec2 describe-instances \
  --region "${REGION}" \
  --filters "Name=tag:Tier,Values=db" \
            "Name=tag:Environment,Values=${ENV}" \
            "Name=instance-state-name,Values=running" \
  --query 'Reservations[0].Instances[0].PrivateIpAddress' \
  --output text)

for var in nat_eip web_eip app_private_ip db_private_ip; do
  val="${!var}"
  if [[ -z "$val" || "$val" == "None" ]]; then
    echo "ERROR: Could not resolve ${var}. Is terraform apply complete and instances running?"
    exit 1
  fi
done

cat > "${OUT_FILE}" <<EOF
---
# Auto-generated by scripts/ansible-sync.sh — do not edit manually.
# Run 'make ansible-sync' to refresh after terraform apply.
nat_eip: "${nat_eip}"
web_eip: "${web_eip}"
app_private_ip: "${app_private_ip}"
db_private_ip: "${db_private_ip}"
EOF

echo "[ansible-sync] Written to ${OUT_FILE}"
echo "  nat_eip        = ${nat_eip}"
echo "  web_eip        = ${web_eip}"
echo "  app_private_ip = ${app_private_ip}"
echo "  db_private_ip  = ${db_private_ip}"
